// Textures. Everything here is generated at boot into a canvas so the game is
// playable with zero asset files — but any name listed in REAL is loaded from
// assets/tex/<name>.png instead. Drop a generated PNG in, add the name, done.
import * as THREE from 'three';

// Generated by tools/gentex.js (Krea 2 Turbo) and made to wrap by
// tools/seamless.py. The procedural recipes below stay as the fallback for
// anything not listed here — the game must never need an asset file to boot.
export const REAL = new Set([
  'grass', 'dirt', 'rock', 'sand', 'wood', 'ice', 'metal', 'water', 'crate',
]);

/* ------------------------------------------------------------------ noise */
const rng = s => () => (s = (s * 1664525 + 1013904223) >>> 0) / 4294967296;

// Tileable value noise: a LxL lattice sampled with wraparound, so the texture
// seams match no matter how many octaves we stack.
function lattice(L, r) { const a = new Float32Array(L * L); for (let i = 0; i < a.length; i++) a[i] = r(); return a; }
function at(a, L, x, y) { return a[(((y % L) + L) % L) * L + (((x % L) + L) % L)]; }
function value(a, L, x, y) {
  const x0 = Math.floor(x), y0 = Math.floor(y);
  const u = (t => t * t * (3 - 2 * t))(x - x0), v = (t => t * t * (3 - 2 * t))(y - y0);
  const a00 = at(a, L, x0, y0), a10 = at(a, L, x0 + 1, y0), a01 = at(a, L, x0, y0 + 1), a11 = at(a, L, x0 + 1, y0 + 1);
  return (a00 * (1 - u) + a10 * u) * (1 - v) + (a01 * (1 - u) + a11 * u) * v;
}
// fbm over `oct` octaves, all tileable across a [0,1) square.
function fbm(seed, oct = 4, base = 4) {
  const r = rng(seed), ls = [];
  for (let o = 0; o < oct; o++) { const L = base << o; ls.push([lattice(L, r), L]); }
  return (x, y) => {
    let n = 0, amp = 1, tot = 0;
    for (const [a, L] of ls) { n += amp * value(a, L, x * L, y * L); tot += amp; amp *= 0.5; }
    return n / tot;
  };
}

/* ------------------------------------------------------- pixel-level paint */
const mix = (a, b, t) => [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t];
const hex = h => [(h >> 16 & 255), (h >> 8 & 255), (h & 255)];
// JS `%` keeps the sign, which tears a tiling pattern wherever the argument
// goes negative. This is the one that wraps.
const frac = v => v - Math.floor(v);

// Paint an SxS canvas by calling shade(x01, y01, noiseFns) -> [r,g,b] 0-255.
function paint(S, shade) {
  const cv = document.createElement('canvas'); cv.width = cv.height = S;
  const ctx = cv.getContext('2d'), img = ctx.createImageData(S, S), d = img.data;
  for (let y = 0; y < S; y++) for (let x = 0; x < S; x++) {
    const c = shade(x / S, y / S), i = (y * S + x) * 4;
    d[i] = c[0]; d[i + 1] = c[1]; d[i + 2] = c[2]; d[i + 3] = c.length > 3 ? c[3] : 255;
  }
  ctx.putImageData(img, 0, 0);
  return cv;
}

/* ------------------------------------------------------------- the recipes */
// Each returns a canvas. Kept deliberately chunky — N64 silhouettes, but the
// texel density is modern so nothing turns to mud up close.
const RECIPES = {
  grass() {
    const n = fbm(11, 5, 6), blade = fbm(77, 2, 24);
    const dark = hex(0x2f7d32), lite = hex(0x7cc242), dry = hex(0xb9c94a);
    return paint(256, (x, y) => {
      const v = n(x, y), b = blade(x, y);
      let c = mix(dark, lite, v * .9 + .1);
      c = mix(c, dry, Math.max(0, b - .62) * 1.6);
      return c.map(k => k * (0.86 + 0.28 * b));
    });
  },
  rock() {
    const n = fbm(23, 5, 4), crack = fbm(41, 3, 8);
    const a = hex(0x4a4f5e), b = hex(0x9aa2b4);
    return paint(256, (x, y) => {
      const v = n(x, y), k = Math.abs(crack(x, y) - .5);
      const c = mix(a, b, v);
      return c.map(q => q * (k < .04 ? .55 : 1));   // dark fracture lines
    });
  },
  dirt() {
    const n = fbm(31, 5, 5), grit = fbm(59, 2, 40);
    const a = hex(0x6b4526), b = hex(0xa9743f);
    return paint(256, (x, y) => mix(a, b, n(x, y) * .8 + grit(x, y) * .2));
  },
  sand() {
    const n = fbm(13, 4, 6), rip = fbm(67, 2, 3);
    const a = hex(0xd9bc7a), b = hex(0xf5e3b3);
    return paint(256, (x, y) => {
      const ripple = Math.sin((y + rip(x, y) * .3) * Math.PI * 16) * .5 + .5;
      return mix(a, b, n(x, y) * .6 + ripple * .4);
    });
  },
  wood() {
    const n = fbm(83, 4, 8);
    const a = hex(0x6d4321), b = hex(0xc08a4a);
    return paint(256, (x, y) => {
      const ring = Math.sin((x * 9 + n(x, y) * 2.2) * Math.PI) * .5 + .5;
      return mix(a, b, ring * .7 + n(x, y) * .3);
    });
  },
  crate() {
    const wood = RECIPES.wood();
    const cv = document.createElement('canvas'); cv.width = cv.height = 256;
    const g = cv.getContext('2d');
    g.drawImage(wood, 0, 0);
    g.strokeStyle = 'rgba(60,32,12,.85)'; g.lineWidth = 14;
    g.strokeRect(7, 7, 242, 242);                       // frame
    g.lineWidth = 9; g.beginPath();
    g.moveTo(14, 14); g.lineTo(242, 242); g.moveTo(242, 14); g.lineTo(14, 242);
    g.stroke();                                          // the classic X
    g.fillStyle = 'rgba(255,255,255,.10)'; g.fillRect(0, 0, 256, 26);
    return cv;
  },
  ice() {
    const n = fbm(97, 5, 4);
    const a = hex(0x7fc7e8), b = hex(0xe8fbff);
    return paint(256, (x, y) => {
      const v = n(x, y);
      return mix(a, b, v * v * 1.25).map(k => Math.min(255, k));
    });
  },
  lava() {
    const n = fbm(103, 5, 5);
    const cool = hex(0x2b0a06), hot = hex(0xffd166), mid = hex(0xe8460f);
    return paint(256, (x, y) => {
      const v = n(x, y);
      return v < .5 ? mix(cool, mid, v * 2) : mix(mid, hot, (v - .5) * 2);
    });
  },
  water() {
    const n = fbm(151, 4, 5);
    const a = hex(0x0e5c8a), b = hex(0x3fb6d8);
    return paint(256, (x, y) => mix(a, b, n(x, y)));
  },
  // --- the desert set ---
  // Wind-cut sandstone: horizontal strata, because a mesa reads as a mesa from
  // the banding and from nothing else. The bands wobble with the noise rather
  // than running dead straight — a ruled line looks like a barcode at this
  // texel density, which is what the first pass looked like.
  sandstone() {
    const n = fbm(307, 4, 5), grit = fbm(311, 2, 32);
    const a = hex(0x9c5a34), b = hex(0xd99b5c), c = hex(0xf0cf9a);
    return paint(256, (x, y) => {
      const band = Math.sin((y * 7 + n(x, y) * 2.4) * Math.PI) * .5 + .5;
      const base = mix(a, b, band);
      return mix(base, c, Math.max(0, n(x, y) - .55) * 1.5)
        .map(k => k * (0.92 + 0.16 * grit(x, y)));
    });
  },
  // --- the moon set ---
  // Regolith: grey dust with craters bitten out of it. The craters are the
  // whole texture — flat grey noise at this scale is concrete, and a moon made
  // of concrete is a car park.
  regolith() {
    const n = fbm(401, 5, 6), pit = fbm(409, 3, 11), grit = fbm(419, 2, 48);
    const a = hex(0x6a6f88), b = hex(0xb4b9cf);
    return paint(256, (x, y) => {
      const v = n(x, y), p = pit(x, y);
      // A crater is a shallow bowl with a slightly brighter rim. The numbers
      // are deliberately gentle: the first pass used a hard dark/light split
      // and a wide low band, and 256px of that at platform scale is not the
      // moon, it is camouflage netting. Small pits, small contrast, and the
      // fine grit on top is what actually sells the dust.
      const rim = Math.abs(p - .32) < .03 ? 1.10 : (p < .32 ? .86 : 1);
      return mix(a, b, v * .7 + .15)
        .map(k => Math.min(255, k * rim * (0.94 + 0.12 * grit(x, y))));
    });
  },
  // --- the flight level's industrial set ---
  // Ice pads and grey rock in a space station read as a glacier someone parked
  // a gate on. These two replace them, and the light/dark split is not
  // decoration: `deck` is what you LAND on and `panel` is what you must not hit,
  // so the pads have to pop out of the walls the way the ice used to.
  deck() {
    const n = fbm(211, 4, 8), wear = fbm(233, 3, 5);
    const a = hex(0x6b7686), b = hex(0xc2ccd9), mark = hex(0xd8a63a);
    return paint(256, (x, y) => {
      // Two mirrored diagonal families = the classic diamond tread plate. The
      // frequency must be a whole number or the pattern tears at the seam.
      const F = 10;
      const d1 = Math.abs(frac((x + y) * F) - .5);
      const d2 = Math.abs(frac((x - y) * F) - .5);
      const tread = Math.max(0, .5 - Math.min(d1, d2) * 2.4);
      let c = mix(a, b, n(x, y) * .4 + tread * 1.25);
      const w = wear(x, y);
      if (w > .72) c = mix(c, mark, (w - .72) * 2.4);      // scuffed safety paint
      return c.map(k => Math.min(255, k));
    });
  },
  panel() {
    const n = fbm(251, 4, 6), grime = fbm(269, 2, 16);
    const a = hex(0x2c3341), b = hex(0x59647a), rivet = hex(0x93a0b6);
    return paint(256, (x, y) => {
      const P = 4;                                    // 4x4 plates across the tile
      const u = frac(x * P), v = frac(y * P);
      let c = mix(a, b, n(x, y) * .75 + .12);
      if (Math.min(u, 1 - u, v, 1 - v) < .035) c = c.map(k => k * .5);   // recessed seam
      const r = Math.hypot(Math.min(u, 1 - u) - .08, Math.min(v, 1 - v) - .08);
      if (r < .024) c = mix(c, rivet, .85);            // a rivet inside each corner
      return c.map(k => k * (.86 + .26 * grime(x, y)));
    });
  },
  metal() {
    const n = fbm(199, 3, 32);
    const a = hex(0x555f70), b = hex(0xb9c4d6);
    return paint(256, (x, y) => {
      const band = Math.sin(y * Math.PI * 8) * .5 + .5;
      return mix(a, b, n(x, y) * .5 + band * .5);
    });
  },
  // Orion's skin/cloth atlas is drawn, not noised — it needs to read as a face.
  orion() { return orionAtlas(); },
  // Same 256px layout, armoured. Worn only in the flight level.
  orionSuit() { return orionSuitAtlas(); },
};

/* ------------------------------------------------- the character texture */
// A 256x256 atlas. UV regions (in 0-1) are declared in player.js FACE/etc so
// a hand-painted or AI-painted replacement only has to match this layout:
//   (0,0)-(.5,.5)  head front   (.5,0)-(1,.5)  head sides/back
//   (0,.5)-(.5,1)  torso        (.5,.5)-(1,1)  limbs / hair
function orionAtlas() {
  const S = 256, cv = document.createElement('canvas'); cv.width = cv.height = S;
  const g = cv.getContext('2d');
  const px = (x, y, w, h, c) => { g.fillStyle = c; g.fillRect(x * S, y * S, w * S, h * S); };

  px(0, 0, 1, 1, '#f0c39a');                       // base skin everywhere
  // --- head front quadrant ---
  px(0, 0, .5, .5, '#f7cfa6');
  px(0, 0, .5, .13, '#3a2a1c');                    // fringe
  px(.09, .17, .09, .07, '#ffffff'); px(.32, .17, .09, .07, '#ffffff');  // eye whites
  px(.12, .19, .05, .05, '#2b1d12'); px(.35, .19, .05, .05, '#2b1d12');  // pupils
  px(.135, .20, .018, .018, '#ffffff'); px(.365, .20, .018, .018, '#ffffff'); // glints
  px(.16, .33, .18, .04, '#c8654f');               // grin
  px(.05, .28, .07, .045, '#ffb0a0'); px(.38, .28, .07, .045, '#ffb0a0');  // cheeks
  // --- head sides/back ---
  px(.5, 0, .5, .5, '#f2c69c');
  px(.5, 0, .5, .17, '#3a2a1c');                   // hair wrap
  px(.5, .17, .06, .1, '#e8b98e');                 // ear
  // --- torso: the star hoodie ---
  px(0, .5, .5, .5, '#2f6fdc');
  px(0, .5, .5, .07, '#1e4fa8');                   // collar
  px(.16, .62, .18, .18, '#ffd23f');               // chest star (blocked out)
  px(.20, .60, .10, .06, '#ffd23f'); px(.13, .70, .24, .06, '#ffd23f');
  px(0, .93, .5, .07, '#1e4fa8');                  // hem
  // --- limbs quadrant: sleeve blue over shorts red over shoe ---
  px(.5, .5, .5, .18, '#2f6fdc');                  // sleeve
  px(.5, .68, .5, .16, '#d13b4a');                 // shorts
  px(.5, .84, .5, .16, '#f0c39a');                 // leg skin
  px(.5, .93, .5, .07, '#f4f4f4');                 // sock/shoe
  return cv;
}

/**
 * The flight suit. Same 256px atlas layout as `orionAtlas` — it has to be, the
 * UV rects in player.js are shared — so this is a straight repaint: red plate,
 * gold trim, a gold faceplate with lit eye slits, and a reactor on the chest.
 *
 * Deliberately its OWN shapes rather than anyone else's: blocky N64 plates, a
 * wedge faceplate and a three-ring reactor. It should read as "Orion built
 * himself a flying suit", which is the story, not as merchandise.
 */
function orionSuitAtlas() {
  const S = 256, cv = document.createElement('canvas'); cv.width = cv.height = S;
  const g = cv.getContext('2d');
  const px = (x, y, w, h, c) => { g.fillStyle = c; g.fillRect(x * S, y * S, w * S, h * S); };
  const disc = (x, y, r, c) => {
    g.fillStyle = c; g.beginPath(); g.arc(x * S, y * S, r * S, 0, Math.PI * 2); g.fill();
  };
  const RED = '#c22532', RED_D = '#8b141f', GOLD = '#e9b93e', GOLD_D = '#b3852a';
  const DARK = '#242a36', GLOW = '#cdf4ff';

  px(0, 0, 1, 1, RED);
  // --- head front: gold faceplate, lit slits ---
  px(0, 0, .5, .5, RED);
  px(.05, .07, .40, .33, GOLD);
  px(.05, .07, .40, .035, GOLD_D);                 // brow shadow
  px(.05, .36, .40, .04, GOLD_D);                  // jaw shadow
  px(.09, .18, .12, .055, GLOW);                   // eye slits
  px(.29, .18, .12, .055, GLOW);
  px(.15, .30, .20, .025, DARK);                   // mouth vent
  // --- head sides / back: helmet ---
  px(.5, 0, .5, .5, RED);
  px(.5, 0, .5, .17, RED_D);                       // crown (the HAIR rect)
  px(.5, .21, .5, .045, GOLD_D);                   // side band
  px(.5, .30, .09, .10, DARK);                     // ear intake
  // --- torso ---
  px(0, .5, .5, .5, RED);
  px(0, .5, .5, .07, GOLD_D);                      // collar
  px(.03, .60, .44, .26, RED_D);                   // chest plate
  disc(.25, .70, .105, GOLD);                      // the reactor, three rings
  disc(.25, .70, .075, GLOW);
  disc(.25, .70, .035, '#ffffff');
  px(0, .93, .5, .07, GOLD_D);                     // hem
  // --- limbs quadrant: sleeve / hip / leg / boot ---
  px(.5, .5, .5, .18, RED);
  px(.5, .68, .5, .16, GOLD);                      // hip armour
  px(.5, .84, .5, .16, RED);
  px(.5, .93, .5, .07, GOLD);                      // boot
  return cv;
}

/* ------------------------------------------------- crate face stencils */
// The special crates used to differ from a plain one only by a tint, which is
// invisible at a glance and worse than useless in shadow. Each now wears its
// own stencil on every face — plus its own topper, built in world.js, so the
// silhouette gives it away before you can even read the face.
//
// Drawn unlit and transparent, so the symbol stays legible on the shadowed
// side of the crate.
function starPath(g, cx, cy, r) {
  g.beginPath();
  for (let i = 0; i < 10; i++) {
    const rr = i % 2 ? r * .44 : r, a = -Math.PI / 2 + i * Math.PI / 5;
    const x = cx + Math.cos(a) * rr, y = cy + Math.sin(a) * rr;
    i ? g.lineTo(x, y) : g.moveTo(x, y);
  }
  g.closePath();
}

const SYMBOL = {
  // Five-pointed star: this crate is worth a pile of them.
  star(g, S) {
    g.lineJoin = 'round';
    starPath(g, S / 2, S / 2, S * .38);
    g.fillStyle = '#ffd23f'; g.fill();
    g.strokeStyle = '#5a3d00'; g.lineWidth = S * .055; g.stroke();
  },
  // Sootie. The lives counter is a cat, so the 1-UP crate is a cat.
  life(g, S) {
    const u = S / 100, cx = S / 2;
    g.fillStyle = '#2b2431'; g.strokeStyle = '#2b2431';
    g.lineJoin = 'round'; g.lineWidth = 3 * u;
    for (const s of [-1, 1]) {                       // ears
      g.beginPath();
      g.moveTo(cx + s * 30 * u, 34 * u);
      g.lineTo(cx + s * 34 * u, 8 * u);
      g.lineTo(cx + s * 6 * u, 26 * u);
      g.closePath(); g.fill(); g.stroke();
    }
    g.beginPath();                                   // head
    g.ellipse(cx, 56 * u, 33 * u, 29 * u, 0, 0, Math.PI * 2);
    g.fill(); g.stroke();
    g.fillStyle = '#8ff0b4';                         // eyes
    for (const s of [-1, 1]) {
      g.beginPath(); g.ellipse(cx + s * 13 * u, 51 * u, 7 * u, 9 * u, 0, 0, Math.PI * 2); g.fill();
    }
    g.fillStyle = '#2b2431';
    for (const s of [-1, 1]) {
      g.beginPath(); g.ellipse(cx + s * 13 * u, 51 * u, 2.4 * u, 8 * u, 0, 0, Math.PI * 2); g.fill();
    }
    g.fillStyle = '#ff9db0';                         // nose
    g.beginPath(); g.moveTo(cx, 68 * u); g.lineTo(cx - 5 * u, 62 * u); g.lineTo(cx + 5 * u, 62 * u);
    g.closePath(); g.fill();
    g.strokeStyle = '#ffffff'; g.lineWidth = 2.6 * u; // whiskers
    for (const s of [-1, 1]) for (const dy of [-3, 3]) {
      g.beginPath(); g.moveTo(cx + s * 16 * u, (65 + dy) * u); g.lineTo(cx + s * 44 * u, (60 + dy * 2) * u); g.stroke();
    }
  },
  // Three chevrons and a plate: this one throws you up in the air.
  spring(g, S) {
    const u = S / 100, cx = S / 2;
    g.lineCap = 'round'; g.lineJoin = 'round';
    for (let i = 0; i < 3; i++) {
      const y = (34 + i * 21) * u;
      g.beginPath();
      g.moveTo(cx - 27 * u, y + 16 * u); g.lineTo(cx, y); g.lineTo(cx + 27 * u, y + 16 * u);
      g.strokeStyle = '#0b3a5c'; g.lineWidth = 15 * u; g.stroke();
      g.strokeStyle = '#dff2ff'; g.lineWidth = 8 * u; g.stroke();
    }
    g.beginPath(); g.moveTo(cx - 30 * u, 92 * u); g.lineTo(cx + 30 * u, 92 * u);
    g.strokeStyle = '#0b3a5c'; g.lineWidth = 14 * u; g.stroke();
    g.strokeStyle = '#dff2ff'; g.lineWidth = 7 * u; g.stroke();
  },
  // A lit fuse. This one takes its neighbours with it, so the stencil has to
  // say DANGER from across the level: a fat sputtering wick, not a word.
  tnt(g, S) {
    const u = S / 100, cx = S / 2;
    g.lineCap = 'round'; g.lineJoin = 'round';
    // The stick: three bands, because one red rectangle is a brick.
    g.fillStyle = '#c62b2b';
    g.fillRect(cx - 30 * u, 40 * u, 60 * u, 50 * u);
    g.fillStyle = '#f4e2c0';
    for (const y of [50, 74]) g.fillRect(cx - 30 * u, y * u, 60 * u, 9 * u);
    g.strokeStyle = '#4a1010'; g.lineWidth = 5 * u;
    g.strokeRect(cx - 30 * u, 40 * u, 60 * u, 50 * u);
    // The fuse, curling off to one side so it doesn't read as an aerial.
    g.beginPath();
    g.moveTo(cx, 40 * u);
    g.bezierCurveTo(cx + 4 * u, 26 * u, cx + 26 * u, 26 * u, cx + 24 * u, 12 * u);
    g.strokeStyle = '#6b5a3a'; g.lineWidth = 7 * u; g.stroke();
    // The spark.
    for (const [r, c] of [[13, '#ff8a3d'], [7, '#fff3b0']]) {
      g.beginPath(); g.arc(cx + 24 * u, 10 * u, r * u, 0, Math.PI * 2);
      g.fillStyle = c; g.fill();
    }
  },
  // Rivets and a band: this one shrugs off a spin and a stomp. Only a ground
  // pound opens it, so the stencil is the heaviest thing in the set.
  iron(g, S) {
    const u = S / 100, cx = S / 2, cy = S / 2;
    g.fillStyle = '#7d8697';
    g.fillRect(18 * u, 18 * u, 64 * u, 64 * u);
    g.strokeStyle = '#39404f'; g.lineWidth = 7 * u;
    g.strokeRect(18 * u, 18 * u, 64 * u, 64 * u);
    g.fillStyle = '#39404f';                          // the strap
    g.fillRect(18 * u, cy - 9 * u, 64 * u, 18 * u);
    g.fillStyle = '#c7cedb';
    for (const x of [30, cx / u, 70]) for (const y of [28, 72]) {
      g.beginPath(); g.arc(x * u, y * u, 6 * u, 0, Math.PI * 2); g.fill();
    }
    // A down arrow through the strap: the crate tells you which button.
    g.strokeStyle = '#ffd23f'; g.lineWidth = 9 * u; g.lineCap = 'round';
    g.beginPath();
    g.moveTo(cx, cy - 20 * u); g.lineTo(cx, cy + 18 * u);
    g.moveTo(cx - 14 * u, cy + 4 * u); g.lineTo(cx, cy + 18 * u);
    g.lineTo(cx + 14 * u, cy + 4 * u);
    g.stroke();
  },
  // A heart. Same shape as the HUD, on purpose — a kid should not have to be
  // told what refills the hearts.
  heart(g, S) {
    const u = S / 100, cx = S / 2;
    g.beginPath();
    g.moveTo(cx, 84 * u);
    g.bezierCurveTo(cx - 52 * u, 52 * u, cx - 34 * u, 14 * u, cx, 34 * u);
    g.bezierCurveTo(cx + 34 * u, 14 * u, cx + 52 * u, 52 * u, cx, 84 * u);
    g.closePath();
    g.fillStyle = '#ff5d73'; g.fill();
    g.strokeStyle = '#6b1224'; g.lineWidth = 6 * u; g.lineJoin = 'round'; g.stroke();
    g.beginPath();                                   // the shine
    g.ellipse(cx - 15 * u, 44 * u, 7 * u, 11 * u, -.5, 0, Math.PI * 2);
    g.fillStyle = 'rgba(255,255,255,.75)'; g.fill();
  },
};

const faceCache = new Map();
/** Transparent stencil for a crate kind, or null for a plain crate. */
export function crateFace(kind) {
  if (!SYMBOL[kind]) return null;
  if (!faceCache.has(kind)) {
    const S = 128, cv = document.createElement('canvas');
    cv.width = cv.height = S;
    SYMBOL[kind](cv.getContext('2d'), S);
    const t = new THREE.CanvasTexture(cv);
    t.colorSpace = THREE.SRGBColorSpace;
    faceCache.set(kind, t);
  }
  return faceCache.get(kind);
}

/**
 * A portal placard for the hub: level name over a star tally, on a rounded
 * plate tinted to that level's sky. Drawn rather than modelled because text is
 * the one thing ~30 boxes cannot do, and a kid picking a level needs to read
 * which one it is without a manual.
 */
export function signTexture(title, sub, accent = 0x2f6fdc) {
  const W = 512, H = 176;
  const cv = document.createElement('canvas'); cv.width = W; cv.height = H;
  const g = cv.getContext('2d');
  const col = `#${(accent & 0xffffff).toString(16).padStart(6, '0')}`;
  const round = (x, y, w, h, r) => {
    g.beginPath();
    g.moveTo(x + r, y); g.arcTo(x + w, y, x + w, y + h, r);
    g.arcTo(x + w, y + h, x, y + h, r); g.arcTo(x, y + h, x, y, r);
    g.arcTo(x, y, x + w, y, r); g.closePath();
  };
  g.clearRect(0, 0, W, H);
  round(6, 6, W - 12, H - 12, 26); g.fillStyle = 'rgba(10,14,30,.88)'; g.fill();
  g.lineWidth = 9; g.strokeStyle = col; g.stroke();
  g.textAlign = 'center';
  g.fillStyle = '#ffffff';
  g.font = 'bold 54px system-ui,-apple-system,"Segoe UI",sans-serif';
  g.fillText(title, W / 2, 76, W - 60);
  g.fillStyle = '#ffd23f';
  g.font = 'bold 40px system-ui,-apple-system,"Segoe UI",sans-serif';
  g.fillText(sub, W / 2, 132, W - 60);
  const t = new THREE.CanvasTexture(cv);
  t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

/* ---------------------------------------------------------------- loading */
const cache = new Map();
const loader = new THREE.TextureLoader();

function finish(tex, repeat) {
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.wrapS = tex.wrapT = THREE.RepeatWrapping;
  tex.anisotropy = 8;
  if (repeat) tex.repeat.set(repeat, repeat);
  return tex;
}

/** Texture by name. Same name always returns the same texture object. */
export function tex(name, repeat = 1) {
  const key = name + '@' + repeat;
  if (cache.has(key)) return cache.get(key);
  let t;
  if (REAL.has(name)) {
    t = loader.load(`./assets/tex/${name}.jpg`);
  } else {
    const make = RECIPES[name];
    if (!make) throw new Error(`no texture recipe: ${name}`);
    t = new THREE.CanvasTexture(make());
  }
  cache.set(key, finish(t, repeat));
  return cache.get(key);
}

/** Sky: a vertical gradient baked to a texture and mapped on the scene bg. */
export function skyTexture(top, bottom, hazeAt = 0.62) {
  const cv = document.createElement('canvas'); cv.width = 4; cv.height = 256;
  const g = cv.getContext('2d'), grd = g.createLinearGradient(0, 0, 0, 256);
  grd.addColorStop(0, `#${top.toString(16).padStart(6, '0')}`);
  grd.addColorStop(hazeAt, `#${bottom.toString(16).padStart(6, '0')}`);
  grd.addColorStop(1, `#${bottom.toString(16).padStart(6, '0')}`);
  g.fillStyle = grd; g.fillRect(0, 0, 4, 256);
  const t = new THREE.CanvasTexture(cv);
  t.colorSpace = THREE.SRGBColorSpace;
  t.mapping = THREE.EquirectangularReflectionMapping;
  return t;
}
