// GENERATED by tools/looppoints.js — do not hand-edit.
// Seconds. Playback runs 0..loopEnd once (the intro), then repeats
// loopStart..loopEnd forever via WebAudio's native loop points.
export const LOOPS = {
  "jungle": {
    "loopStart": 35.4801,
    "loopEnd": 54.8624
  },
  "coast": {
    "loopStart": 34.8996,
    "loopEnd": 59.3602
  },
  "title": {
    "loopStart": 4.9923,
    "loopEnd": 24.2047
  },
  "cosmic": {
    "loopStart": 32.3918,
    "loopEnd": 67.6264
  },
  "frost": {
    "loopStart": 13.3979,
    "loopEnd": 35.8708
  },
  "reef": {
    "loopStart": 30.7897,
    "loopEnd": 91.3093
  }
};
