// GENERATED by tools/looppoints.js — do not hand-edit.
// Seconds. Playback runs 0..loopEnd once (the intro), then repeats
// loopStart..loopEnd forever via WebAudio's native loop points.
export const LOOPS = {
  "jungle": {
    "loopStart": 35.4801,
    "loopEnd": 54.8624
  },
  "coast": {
    "loopStart": 47.6241,
    "loopEnd": 94.4376
  },
  "title": {
    "loopStart": 4.9923,
    "loopEnd": 24.2047
  }
};
