// GENERATED by tools/looppoints.js — do not hand-edit.
// Seconds. Playback runs 0..loopEnd once (the intro), then repeats
// loopStart..loopEnd forever via WebAudio's native loop points.
export const LOOPS = {
  "jungle": {
    "loopStart": 35.4801,
    "loopEnd": 54.8624
  },
  "coast": {
    "loopStart": 34.8996,
    "loopEnd": 59.3602
  },
  "title": {
    "loopStart": 4.9923,
    "loopEnd": 24.2047
  },
  "cosmic": {
    "loopStart": 32.3918,
    "loopEnd": 67.6264
  },
  "frost": {
    "loopStart": 13.3979,
    "loopEnd": 35.8708
  },
  "reef": {
    "loopStart": 30.7897,
    "loopEnd": 91.3093
  },
  "dunes": {
    "loopStart": 64.3889,
    "loopEnd": 87.8393
  },
  "cavern": {
    "loopStart": 15.0233,
    "loopEnd": 68.3454
  },
  "lunar": {
    "loopStart": 28.1658,
    "loopEnd": 56.0471
  },
  "skyway": {
    "loopStart": 35.4801,
    "loopEnd": 82.2786
  },
  "castle": {
    "loopStart": 15.9289,
    "loopEnd": 56.1639
  }
};
